services:
  api:
    image: ${IMAGE_API:-osm-speed-api:latest}
    build:
      context: .
      dockerfile: Dockerfile

  importer:
    image: ${IMAGE_IMPORTER:-osm-speed-importer:latest}
    build:
      context: .
      dockerfile: docker/importer/Dockerfile
